// Generated by https://quicktype.io

export class Node {
  /**
   * Crea una instancia del objeto nodo.
   * @param {number} id ID del nodo
   * @param {string} str_SISTEMA
   * @param {string} str_CENTRO_DE_CONTROL_REGIONAL
   * @param {string} str_ZONA_DE_CARGA
   * @param {string} str_CLAVE
   * @param {string} str_NOMBRE
   * @param {number} int_NIVEL_DE_TENSION
   * @param {string} str_ZONA_DE_OPERACION_DE_TRANSMISION
   * @param {string} str_GERENCIA_REGIONAL_DE_TRANSMISION
   * @param {string} str_ZONA_DE_DISTRIBUCION
   * @param {string} str_GERENCIA_DIVISIONAL_DE_DISTRIBUCION
   * @param {number} int_INEGI_CLAVE_ENTIDAD_FEDERATIVA
   * @param {string} str_INEGI_ENTIDAD_FEDERATIVA
   * @param {number} int_INEGI_CLAVE_MUNICIPIO
   * @param {string} str_INEGI_MUNICIPIO
   * @param {string} str_REGION_DE_TRANSMISION
   * @memberof Node
   */
  constructor(
    public id: number,
    public str_SISTEMA: string,
    public str_CENTRO_DE_CONTROL_REGIONAL: string,
    public str_ZONA_DE_CARGA: string,
    public str_CLAVE: string,
    public str_NOMBRE: string,
    public int_NIVEL_DE_TENSION: number,
    public str_ZONA_DE_OPERACION_DE_TRANSMISION: string,
    public str_GERENCIA_REGIONAL_DE_TRANSMISION: string,
    public str_ZONA_DE_DISTRIBUCION: string,
    public str_GERENCIA_DIVISIONAL_DE_DISTRIBUCION: string,
    public int_INEGI_CLAVE_ENTIDAD_FEDERATIVA: number,
    public str_INEGI_ENTIDAD_FEDERATIVA: string,
    public int_INEGI_CLAVE_MUNICIPIO: number,
    public str_INEGI_MUNICIPIO: string,
    public str_REGION_DE_TRANSMISION: string
  ) { }
}
