// Generated by https://quicktype.io

export class ErrorLog {
  /**
   * Creates an instance of ErrorLog.
   * @param {number} id
   * @param {string} str_description
   * @param {string} str_extraInfo
   * @param {string[]} ser_CLAVES
   * @param {string} str_SISTEMA
   * @param {string} str_PROCESO
   * @param {string} date_FECHA_PETICION
   * @param {boolean} bool_resuelto
   * @param {string} created_at
   * @param {string} resolved_at
   * @memberof ErrorLog
   */
  constructor(
    public id: number,
    public str_description: string,
    public str_extraInfo: string,
    public ser_CLAVES: string[],
    public str_SISTEMA: string,
    public str_PROCESO: string,
    public date_FECHA_PETICION: string,
    public bool_resuelto: boolean,
    public created_at: string,
    public resolved_at: string) { }
}
